return {
  "folke/lazy.nvim",
  { import = "user.plugins.colorschemes" },
  { import = "user.plugins.ide" },
  { import = "user.plugins.productivity" },
  { import = "user.plugins.debuggers" },
  { import = "user.plugins.ai" },
  { import = "user.plugins.autocomplete" },
  { import = "user.plugins.treesitter" },
  { import = "user.plugins.navigation" },
  { import = "user.plugins.ui" },
  { import = "user.plugins.git" },
  { import = "user.plugins.session-management" },
  { import = "user.plugins.utils" },
  { import = "user.plugins.lsp" },
  { import = "user.plugins.syntax-highlighting" },
}
